### PR TITLE
feat: IfFunc

### PR DESCRIPTION
**Pull request by XangelMusic**
Including a IfFunc that implements a function using the chosen element as the parameter.

### CODE REVIEW

**Comment by julien040** [comment]
Hi @XangelMusic, I never thought I would receive a PR for this library, but here we are. Your changes are interesting; thank you for making them. I just have a little suggestion.

Why not change the signature of `IfFunc` to
```go
func IfFunc[T any, R any](condition bool, a, b T, f func(T) R) R {
	if condition {
		return f(a)
	}
	return f(b)
}
```

By adding the generic `R`, it means the function can return something other than its parameters. For example
```go
result := IfFunc(true, "foo", "bar", func(t string) int {
		return 2
	})
fmt.Println(result) // 2
```

And it doesn't add any more complexity for the user.

**Comment by XangelMusic** [comment]
Hello @julien040 . Yeah I recently came across this package because I actually needed a ternary package (I made my own generic function exactly like yours but I got into a cyclical issue as expected with Go)

I'll take your suggestion, and I don't mind you rewriting my code since this is still your package.

**Comment by julien040** [comment]
I don't want to take credit for your work. If you have the time, please update the PR, and I'll merge it. Thus, you'll be included in the contributors of this repo.

**Comment by XangelMusic** [comment]
> I don't want to take credit for your work. If you have the time, please update the PR, and I'll merge it. Thus, you'll be included in the contributors of this repo.

Thank you. I just updated the PR so it should be good to go.

**Comment by julien040** [comment]
Sorry to bother you, but there is a missing comma between `T any` and `R any`.
```go
func IfFunc[T any R any](condition bool, a, b T, f func(T) R) R {
```

should be

```go
func IfFunc[T any, R any](condition bool, a, b T, f func(T) R) R {
```

I tried to fix the PR directly, but GitHub seems to refuse it. I'm afraid I might have to ask you to make the change.

**Comment by julien040** [comment]
Perfect ! Thank you

**Pull request merged**
